@baseURL = http://localhost:7072/api/comments/
###
GET {{baseURL}}getAllCommentFromPost/1
###
POST {{baseURL}}updateComment/1
Content-Type: application/json

{
  "commentID": 1,
  "body": "det kan jeg kun give dig ret i!!!!!!!"
}