GET http://localhost:7072/api/msg/hello

###

POST http://localhost:7072/api/auth/register
Content-Type: application/json

{
  "username": "Frederik",
  "password": "1234",
  "email": "Fred@dk.dk"
}

###
POST http://localhost:7072/api/auth/login
Content-Type: application/json

{
  "username": "Frederik",
  "password": "1234",
  "email": "Fred@dk.dk"
}

###

GET http://localhost:7072/api/users/getAll